---
name: 网易云音乐 API
version: v4.14.1
slug: cloud-music
description: 网易云音乐 Node.js API service
url: https://gitcode.com/waxgourd/addons
init: false
codenotary: wghaos@163.com
arch:
  - aarch64
  - amd64
startup: services
image: binaryify/netease_cloud_music_api
ports:
  3000/tcp: 3000
