arch:
  - aarch64
  - amd64
backup_exclude:
  - '*/data/'
codenotary: wghaos@163.com
description: '可帮助你将浏览器书签集中式管理'
devices:
  - /dev/dri
  - /dev/dri/card0
  - /dev/dri/card1
  - /dev/dri/renderD128
  - /dev/vchiq
  - /dev/ttyUSB0
  - /dev/sda
  - /dev/sdb
  - /dev/nvme
  - /dev/nvme0n1p1
  - /dev/nvme0n1p2
  - /dev/mmcblk
  - /dev/fuse
  - /dev/net/tun
host_network: false
ingress: false
ingress_stream: false
init: false
name: OneNav
panel_icon: mdi:network
ports:
  '80': 8880
webui: "http://[HOST]:[PORT:8880]/"
privileged:
  - SYS_ADMIN
  - DAC_READ_SEARCH
slug: onenav
startup: services
boot: auto
url: https://gitcode.com/waxgourd/addons
image: docker.nju.edu.cn/wghaos/onenav
version: v0.9.34
apparmor: true

