name: Portainer汉化版
version: 2.19.1
slug: portainerZH
description: 轻松管理您的Docker环境
codenotary: wghaos@163.com
url: 'https://gitcode.com/waxgourd/addons'
image: wghaos/portainer-zh
arch:
    - aarch64
    - amd64
    - armv7
backup_exclude:
    - backups
    - docker_config/cli-plugins
startup: system
boot: manual
host_network: true
docker_api: true
hassio_api: true
ingress: true
ingress_port: 1337
ingress_stream: true
init: false
map:
    - 'share:rw'
    - ssl
privileged:
    - SYS_ADMIN
    - DAC_READ_SEARCH
full_access: true
hassio_role: admin
udev: true
panel_icon: 'mdi:docker'
ports:
    8000/tcp: null
    9099/tcp: 9000
ports_description:
    8000/tcp: 'Edge Agent Api (Enable when managing remote edge agents)'
    9099/tcp: 'Web UI port'
options:
    certfile: fullchain.pem
    keyfile: privkey.pem
    password: homeassistant
    ssl: false
schema:
    certfile: str
    keyfile: str
    password: 'str?'
    ssl: bool
