name: "Cpolar极点云"
version: '3.3.18'
slug: 'cpolar'
codenotary: wghaos@163.com
description: 'Cpolar 安全的内网穿透工具'
image: wghaos/addon-wghaos-cpolar
url: https://gitcode.com/waxgourd/addons
init: false
arch:
  - aarch64
  - amd64
webui: "[PROTO:http]://[HOST]:[PORT:9200]"
ports:
  9200/tcp: 9200
panel_icon: 'mdi:application-variable'
boot: manual
host_network: true
options:
  Authtoken: ""
schema:
  Authtoken: str?
