name: Onelist
slug: onelist
version: v2.0.5
description: '专注于刮削alist聚合网盘形成影视媒体库的程序'
url: https://gitcode.com/waxgourd/addons
codenotary: wghaos@163.com
image: wghaos/onelist
arch:
  - aarch64
  - amd64
backup_exclude:
  - '*/data/'
devices:
  - /dev/dri
  - /dev/dri/card0
  - /dev/dri/card1
  - /dev/dri/renderD128
  - /dev/vchiq
  - /dev/ttyUSB0
  - /dev/sda
  - /dev/sdb
  - /dev/nvme
  - /dev/nvme0n1p1
  - /dev/nvme0n1p2
  - /dev/mmcblk
  - /dev/fuse
  - /dev/net/tun
apparmor: true
init: false
boot: auto
startup: application
host_network: false
privileged:
  - SYS_ADMIN
  - DAC_READ_SEARCH
ports:
  '5245': 5245
ports_description:
  '5245': web port
webui: "http://[HOST]:[PORT:5245]/"
options:
  env: Release
  title: onelist
  user:
    user_email: admin@qq.com
    user_password: admin
  db:
    db_driver: sqlite
    db_user: root
    db_name: onelist
    db_password_debug: "123456"
    db_password_release: "123456"
  api_secret: zaWs5gGUrYr8czqwlkqVJzDrzMplCzNp
  faviconico_url: https://wework.qpic.cn/wwpic/818353_fizV30xbQCGPQRP_1677394564/0
  download_image: 是
  img_url: https://image.tmdb.org
  video_types: https://image.tmdb.org
  key_db: 22f10ca52f109158ac7fe064ebbcf697
schema:
  env: list(Release|Debug)
  title: str
  user:
    user_email: str
    user_password: str
  db:
    db_driver: str
    db_user: str
    db_name: str
    db_password_debug: str
    db_password_release: str
  api_secret: str
  faviconico_url: str
  download_image: str
  img_url: str
  video_types: str
  key_db: str
