name: 'Excalidraw'
version: '0.17.3'
slug: 'excalidraw'
codenotary: 'wghaos@163.com'
description: "Excalidraw是支持多人协同的私有化在线画板工具"
image: wghaos/excalidraw
url: https://gitcode.com/waxgourd/addons
init: false
arch:
  - aarch64
  - amd64
webui: "[PROTO:http]://[HOST]:[PORT:3000]"
ports:
  3000/tcp: 3000
panel_icon: 'mdi:application-variable'
boot: manual
