name: "WGHAOS SSH 配置器"
version: '0.1.1-34-beta'
slug: 'wghaosssh'
codenotary: wghaos@163.com
description: '这将启用端口22222上的SSH WGHassOS控制台。仅适用于Home Assistant操作系统'
image: registry.wghaos.com/wghaos/addons-wghaos-ssh
url: https://gitcode.com/waxgourd/addons
init: false
arch:
  - aarch64
  - amd64
  - armv7
backup_exclude:
  - '*/data/'
ingress: true
ingress_port: 9876
panel_icon: 'mdi:flower'
boot: manual
privileged:
  - SYS_ADMIN
full_access: true
map:
  - all_addon_configs:rw
  - backup:rw
apparmor: true
docker_api: true
startup: services

